# Job which runs mvn test and verify, Sonar Analysis (if branch is master), mvn install,
# builds Docker image, pushes this to GCR and checks for any image vulnerabilities
parameters:
  - name: 'project'
    default: ''
  - name: 'repoName'
    default: ''
  - name: 'artifactName'
    default: ''
  - name: 'mavenContainer'
    default: 'maven:3-jdk-11'
  - name: 'checkStyleRunAnalysis'
    default: 'true'

jobs:
  - job: buildTestPublishToPipeline
    displayName: 'Test/build app and Dockerimage'
    container: ${{ parameters.mavenContainer }}
    # Job condition: Run these jobs on any branch, but not on tags
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    # Steps in this Job
    steps:
      # Authenticate Maven to Nexus using predefined Service Connections
      # (Project Settings->Pipelines->Service Connections)
      - template: maven/task-maven-complete.yml@{{parameters.templates}}
        parameters:
          checkStyleRunAnalysis: ${{ parameters.checkStyleRunAnalysis }}

      # Publish pipeline artifact
      - publish: target
        displayName: 'Publish artifact to pipeline'
        artifact: ${{ parameters.artifactName }}
